feature: tcc sample
CECTC/dbpack-samples pull request #17
Opened 2022-07-11 08:45 UTC by dk-lockdown

2022-07-11 10:48 UTC, fatelei approved these changes

2022-07-11 13:45 UTC, bohehe requested changes

2022-07-11 13:45 UTC, bohehe commented on tcc/README.md
> +After execute `curl -XPOST http://localhost:8080/transfer-commit`, check log by `docker logs dbpack1`
```suggestion
After executing `curl -XPOST http://localhost:8080/transfer-commit`, check log by `docker logs dbpack1` 
```

2022-07-11 13:45 UTC, bohehe commented on tcc/README.md
> +or `docker logs dbpack2`, then, you will see confirm interface be called automatically.
```suggestion
or `docker logs dbpack2`, then, you will see confirm API been called automatically.
```

2022-07-11 13:45 UTC, bohehe commented on tcc/README.md
> +After execute `curl -XPOST http://localhost:8080/transfer-cancel`, check log by `docker logs dbpack1`
```suggestion
After executing `curl -XPOST http://localhost:8080/transfer-cancel`, check log by `docker logs dbpack1`
```

2022-07-11 13:45 UTC, bohehe commented on tcc/README.md
> +or `docker logs dbpack2`, then, you will see cancel interface be called automatically.
```suggestion
or `docker logs dbpack2`, then, you will see cancel API been called automatically.
```

2022-07-12 00:52 UTC, bohehe approved these changes

2022-07-12 02:03 UTC, merged